### ISSUE TITLE
When A Resource Goes to 0 

### ISSUE THREAD

**Issue by anthonyromyn** [DuncanLab/RoadRAGE#12]
Hi Cody,

I noticed that when the user is driving and one (or both) resources get to 0, nothing happens. I wonder if we could have the software designed so that when a resource gets to 0 the current trial ends and, additionally, we can choose (perhaps in the .json) whether the points collected by the user over the trial get to be kept or whether they get deleted. 

Hope all is well!
Anthony

**Comment by codyhowarth** [comment]
@anthonyromyn would you want this to be a toggle, or should the trial always end when a resource gets to zero?

The points collected option we can add no problem.

**Comment by anthonyromyn** [comment]
@codyhowarth Awesome and the best things would be to have these two options:
1) when a resource bar gets to 0, trial ends
2) turn the resource bar(s) off so that they don't exist. For some trials/studies we'll want to have participants driving and making choices, collecting points/money, but without the need to keep tracking and collecting resources. So just turning the bars off completely and just tracking/collecting points/money, no food or water items/actions.

I can think of a few other potential things that could be cool like resources getting to 0 = slowed movement speed or losing points/money over time (draining) or visuals on-screen change a bit, but the studies we want to run this year don't need anything like that!
