### ISSUE TITLE
Probabilistic Outcomes

### ISSUE THREAD

**Issue by anthonyromyn** [DuncanLab/RoadRAGE#14]
Hi Cody,

Another feature that we would need is probabilistic outcomes. For example, instead of food and water, the first design we want to build will be all about points/money. Players choose a lane and then gain/lose some amount of points/money when they drive into the item on that lane (e.g. instead of a strawberry we'll have dice).  So, when they drive into the dice, maybe they have a 50% chance of winning x points and a 50% chance of losing x points. So could we a) get probabilistic outcomes for the items and b) make it customizable so we can set the %'s and amounts to win or lose differently for different trials?

Thanks!
Anthony

**Comment by codyhowarth** [comment]
@anthonyromyn do you want the points/money to be the values shown on the resource bars? Or will those remain a totally separate feature? If separate, does this require a "points" display somewhere on the screen? Or can the points just be displayed briefly when the user collects the item (as in #15).

**Comment by anthonyromyn** [comment]
@codyhowarth Awesome yeah can it be built so that:
1) points are separate from the resources and resource bar
2) overall points collected are displayed somewhere onscreen (maybe top right or left corner?)
3) the amount of points you just picked up shows up in the middle of the screen briefly (e.g. "+10 points" for maybe 1000 ms)
4) that you can turn on/off options 2 & 3 in the .json.
Less immediate but definitely useful for the future:
5) if the resource bars are toggled on, if one hits 0 and the trial ends, a toggle in the .json to specify whether the user also loses or keeps the points they collected up to that point on the trial

Best,
Anthony
