### ISSUE TITLE
Create option to set user input lock

### ISSUE THREAD

**Issue by codyhowarth** [DuncanLab/RoadRAGE#16]
- Need to specify an option in the config file to allow locking user input after a certain amount of time has passed.

**Comment by codyhowarth** [comment]
This issue is a spin off from #10.

**Comment by codyhowarth** [comment]
@anthonyromyn can you describe your preferred method for setting this option? For example, would you like to set the lock by a time (in ms) since the beginning of the trial?

**Comment by anthonyromyn** [comment]
@codyhowarth hmm yes lock-by-time would be great. If it isn't too much work it would also be great to have an option to place some invisible line/barrier/object that, once they pass through that object, they can no longer control the car. This would just be an alternative to the lock-by-time method, but I could see it being potentially useful. However, if that lock-by-object method would take a significant amount of work then let's just stick with lock-by-time right now!
