### ISSUE TITLE
Output of game events and context to file

### ISSUE THREAD

**Issue by anthonyromyn** [DuncanLab/RoadRAGE#21]
Hi Cody,

Excited about all the new updates! Will test them out this weekend. In the meantime, I think the last big enhancement we would need is an activity log printed to some type of file as an output of the user's session. Could be in .txt, .csv, .tsv, or (probably) anything else, if other types would be better for you. The idea here being that (forgive me if you are already familiar with the topic) while the game is running, the output file is constantly getting new info/lines added to it as a record of what is happening. We can then throw these outputs into stats software for hypothesis testing. So the output file tracks what behaviour users make, when they make them, what the outcomes of their decisions were, what their resources levels were in that moment (if resources were turned on), and such things like this. 

I'll get to writing up a good example of what such an output file might look like and post it here early next week, but wanted to send this message first to touch base/give a bit of context for that future message.

Best,
Anthony

**Comment by codyhowarth** [comment]
Hey Anthony, thanks for the heads up! As for the format of the file, I can make it whatever is easiest for you.

Until you post further details I will start with a `csv` file that contains all trial data we are currently tracking. I think the only difficult part may be tracking the user behaviour. I can output when the user presses a key for now.

**Comment by anthonyromyn** [comment]
Hi Cody,

This is great. Is it also possible to program the software to write an output line every time every time a user presses a button and also every time a user picks up an item/passes through an object?

Best,
Anthony
