### ISSUE TITLE
Fixed minor problems to Run RoadRAGE with Ubuntu 16.04 / Linux 

### ISSUE THREAD

**Issue by anthonyromyn** [DuncanLab/RoadRAGE#4]
Hi RoadRAGE team, 

Awesome project! Excited for the future! I have the software running in Ubuntu 16.04 but encountered a few small problems on the way which don't show up when I run the software on MacOSX just due to difference in folder/pathing rules for the two OS's. So, if any users are using a Linux OS, they can get RoadRAGE running in a minute or two by following what I did below:

Issue 1:
The current master branch of the software contains both an Assets/Scenes and Assets/scenes, highlighted in my folder viewer:
![3](https://user-images.githubusercontent.com/37704753/50116841-49f8f080-0219-11e9-84c7-9f75700c0500.png)

Unity reads the folder structure as if there is only 1 Scenes folder, not distinguishing between the uppercase and lowercase folders, as seen in my projects tab below.
![1](https://user-images.githubusercontent.com/37704753/50116698-e8388680-0218-11e9-912b-250cea0381d3.png)

However, when you try to run a .json with the Start scene, it fails because it can't find the Main scene. See error message in this picture:
![2](https://user-images.githubusercontent.com/37704753/50116709-ed95d100-0218-11e9-8527-fbb35e64a18b.png)

To solve, I just moved Assets/scenes/Start.unity and Assets/scenes/Start.unity.meta to the Assets/Scenes folder and deleted the Assets/scenes folder. All works great after that!

Issue 2:
Related to Issue 1, when users first load the Start scene and then press play, the Config file location gets auto-filled to go to the roadrage json, as seen here:
![4](https://user-images.githubusercontent.com/37704753/50117356-c3451300-021a-11e9-8e42-ce772f9ed87f.png)

However, on Linux machines, this file won't be found because StreamingAssets/config is with a lowercase c in the master branch.
![5](https://user-images.githubusercontent.com/37704753/50117395-dfe14b00-021a-11e9-884a-69b8b1f13547.png)

So, not a big deal, but, the instructions at 

https://github.com/DuncanLab/RoadRAGE -> "3. Set up Unity with RoadRAGE" -> "vi. Once the process is complete, Unity will open. Select the Start scene from Assets/Scenes and press the play button to run the simulation."

Won't work for Linux users. Just wanted to give you a heads-up!

Best,
Anthony

**Comment by codyhowarth** [comment]
Hi @anthonyromyn, this issue should be fixed on master now.

Please open more issues on the repo if you have find any more bugs, or think of a feature request!
